### ISSUE TITLE
Proposta de melhorias no README

### ISSUE THREAD

**Issue by ErickFSilva** [ErickFSilvaProg/desafio-github-markdown#1]
Olá, venho sugerir algumas alterações no seu perfil...
São elas:

1. Edite o terceiro parágrafo, como no exemplo abaixo:
    
    - Durante uma jornada de 10+ anos passei por alguns provedores de internet adquirindo experiências em alguns setores, tais como: suporte ao cliente, monitoramento de redes e suporte interno interno.

2. Após o terceiro parágrafo adicione o seguinte texto:

    - Após alguns anos trabalhando com suporte à usuários estou me preparando, com o auxilio da DIO, para ser programador Java.

**Comment by ErickFSilvaProg** [comment]
Obrigado, vou verificar!

**Comment by ErickFSilvaProg** [comment]
Atualizações realizadas.
